# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "dbsmasher corner"
description: > # this means to ignore newlines until "email:"
   Thoughts, stories and ideas

email: silviamikhail+blog@gmail.com
#blog logo
logo: "/assets/images/unicorn_av.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/backlit-blogging-business-34153.jpg"

name: 'Silvia Botros'
author: 'Silvia Botros'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://blog.dbsmasher.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dbsmasher'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-78506807-1

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dbsmasher
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/silviabotros
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
